#!/usr/bin/env python3
# -*- coding: utf-8 -*- 
import re
from sys import *
import sys
import os
import subprocess
import numpy as np
from numpy import sin,cos,exp,log,tan,sqrt,mean,std,pi,arctan,arcsin,arccos
from scipy import interpolate,integrate
import phys
from os.path import isfile,isdir
from ctypes import *
from struct import *
import h5py
import argparse
from datetime import *
from phys import tbrill,planck
import netCDF4 as nc4

def ecrit1d(f,name,dtype,dimname,data,description=""):
  var=f.createVariable(name,dtype,(dimname,))
  try:
    var[:]=data[:]
  except Exception as e:
    print("-----------------------------------------------------------------------------------")
    print(e)
    print("ecrit1d: problem while writing {:}".format(name))
    print("type({:})={:}".format(name,type(data)))

  if description:
    var.description=description

def ecrit2d(f,name,dtype,dimnames,data,description=""):
  var=f.createVariable(name,dtype,dimnames)
#  print("name",name)
#  print("data.shape",data.shape)
#  print("var.ndims",var.ndim)
  try:
    var[:,:]=data[:,:]
  except Exception as e:
    print("---------------------------------------------------------------------")
    print("var.shape,data.shape",var.shape,data.shape)
    print(e)
    print("ecrit2d: problem while writing {:}".format(name))
    print("type({:})={:}".format(name,type(data)))

  if description:
    var.description=description

def ecrit3d(f,name,dtype,dimnames,data,description=""):
  var=f.createVariable(name,dtype,dimnames)
#  print("name",name)
#  print("data.shape",data.shape)
#  print("var.ndims",var.ndim)
  try:
    var[:,:,:]=data[:,:,:]
  except Exception as e:
    print("---------------------------------------------------------------------")
    print("var.shape,data.shape",var.shape,data.shape)
    print(e)
    print("ecrit2d: problem while writing {:}".format(name))
    print("type({:})={:}".format(name,type(data)))

  if description:
    var.description=description



#f = nc4.Dataset("test.nc", "w", format="NETCDF4")
## f.description: global attribute
#f.description="this file has been generated by creenetcdf.py"
#f.createDimension('x', size=3)
## impossible to create dimensions attributes.
#f.createDimension('y', size=4)
## (name,type,list of dimensions
#t=f.createVariable("temp","f4",("x","y"))
#p=f.createVariable("pressure","f4",("x","y"))
#t[:,:]=300.
#p[:,:]=1.e3
## z.description: variable attribute
#p.description="pressure of grid points"
#t.description="temperature of grid points"
#
#f.close()
#
